server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SPRING_BOOT_DATA?characterEncoding=utf8&useSSL=false
