server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # 将自己注册到eureka server 服务上
  instance:
    prefer-ip-address: true